[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
force_sort_within_sections = true
known_first_party = ["."]
known_third_party = ["numpy","pandas","matplotlib","pytest","sklearn"]

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E","F","W","I","UP"]
ignore = ["E501"]  # 交给 Black 控行宽
fix = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
